config/routes.rb
Doctology::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :posts

  devise_for :users
  root "posts#index"
  get "about" => "pages#about"

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  
  validates :description, presence: true
  validates :image, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_attached_file :avatar, :styles => { :medium => "600x600>", :thumb => "300x300>" }, :default_url => "/images/:style/missing.png"
  
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

 protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def show
  end

  def new
    @post = current_user.posts.build
  end

  def edit
  end

  def create
    @post = current_user.posts.build(post_params)
      if @post.save
        redirect_to @post, notice: 'Post was successfully created.'
      else
        render action: 'new'
    end
  end
  

  def update
      if @post.update(post_params)
        redirect_to @post, notice: 'Post was successfully updated.'
      else
        render action: 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end
    
    def correct_user
      @post = current_user.posts.find_by(id: params[:id])
      redirect_to posts_path, notice: "Not authorized to edit this pin" if @post.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-inverse navbar-default" role="navigation">
	<div class="container">
  	<div class="navbar-header">
    	<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      	<span class="sr-only">Toggle navigation</span>
      	<span class="icon-bar"></span>
      	<span class="icon-bar"></span>
      	<span class="icon-bar"></span>
    	</button>
			<%= link_to "Detroit Receiving Hospital Emergency Medicine", root_path, class: "navbar-brand" %>
		</div>

  <!-- Collect the nav links, forms, and other content for toggling -->
 	 <div class="collapse navbar-collapse navbar-ex1-collapse">
    	<ul class="nav navbar-nav navbar-right">
   		 <li><%= link_to "Home", root_path %></li>
				<li><%= link_to "About", about_path %></li>
				<% if user_signed_in? %>
					<li>
						<%= link_to new_post_path do %>
							<span class="glyphicon glyphicon-plus"></span> New Post
						<% end %>
						</li>
						<li><%= link_to "Account Settings", edit_user_registration_path %></li>
						<li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
						<% else %>
						<li><%= link_to "Sign in", new_user_session_path %></li>
						<% end %>
    	</ul>
  	</div><!-- /.navbar-collapse -->
	</div><!-- /.container-collaps -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Doctology</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<%= render 'layouts/header' %>
<div class ="container">
	<% flash.each do |name, msg| %>
		<%= content_tag(:div, msg, class: "alert alert-info") %>
	<% end %>
	<%= yield %>
</div>

</body>
</html>

app/views/pages/_home.html.erb
<div class="jumbotron center">
<h2>Welcome to DRH-EM Portal!</h2> 
	<p>
		<%= link_to "Log in", new_user_session_path, class: "btn btn-primary" %>
		<%= link_to "Sign up", new_user_registration_path, class: "btn btn-danger" %>
	</p>
</div>

app/views/pages/about.html.erb
<h3>About us</h3>
<p>Detroit Receiving Hospital Emergency Medicine Portal is built on Ruby on Rails!</p>

app/views/posts/_form.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	
	<div class="form-group">
	    <%= f.label :image %>
	    <%= f.file_field :image, class: "form-control" %>
	 </div>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control" %>
  </div>
	
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>

<div id = "posts" class = "transitions-enabled">
    <% @posts.each do |post| %>
      <div class = "box  panel panel-default">
				<%= link_to image_tag(post.image.url(:medium)), post %>
				<div class = "panel-body">
        	<%= post.description %> <br />
					<strong><%= post.user.name if post.user %></strong>
					<% if post.user == current_user %>
						<div class = "actions">
        			<%= link_to edit_post_path(post) do %>
								<span class="glyphicon glyphicon-edit"></span> Edit
							<% end %>
        			<%= link_to method: :delete, data: { confirm: 'Are you sure?' } do %>
							<span class="glyphicon glyphicon-trash"></span>
							Delete
							<% end %>
						</div>
					<% end %>
				</div>
			</div>
    <% end %>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<%= link_to 'Back', posts_path %>

<div class="row">
	<div class = "col-md-offset-2 col-md-8">
		<div class="panel panel-default">
			<div class = "panel-heading center">
				<%= image_tag @post.image.url(:medium) %>
			</div>
			<div class ="panel-body">
				<p> <%= @post.description %> </p>
				<p> <strong><%= @post.user.name if @post.user%></strong></p>

				<% if @post.user == current_user %>
					<%= link_to edit_post_path(@post) do%> 
						<span class="glyphicon glyphicon-edit"></span>
				    Edit
					<% end %>
				<% end %>
			</div>
		</div>
	</div>
</div>